Fix - regex literals
ibis-project/ibis-bigquery pull request #112
Opened 2022-01-26 20:06 UTC by jayceslesar

@cpcloud @tswast Thoughts?

Fixes issue where regexes passed into `re_search` among other `re` functions in the `ibis` library were being converted to strings prefixed with `r'my_original_string'` which seems less than useful if `'my_original_string'` is a regex.

Before generated BigQuery would look like:
```SQL
SELECT *
FROM `my_project.my_dataset.my_table`
WHERE REGEXP_CONTAINS(`field`, r'(some_message_\\(\\(&some_signal\\)\\))')
```
whereas now it looks like:
```SQL
SELECT *
FROM `my_project.my_dataset.my_table`
WHERE REGEXP_CONTAINS(`field`, '(some_message_\\(\\(&some_signal\\)\\))')
```

Will close #110

2022-01-26 20:07 UTC, jayceslesar commented
Sorry for double PR (closed the first one) trying to conform to the conventionalcommits...testing my beginner/medium git

2022-01-26 21:16 UTC, tswast requested changes
Could you add some unit tests to confirm this fix?

2022-01-27 23:21 UTC, jayceslesar commented
@tswast let me know how that test looks, little challenging to conduct a test without a real table with values (probably possible just unsure of syntax). Would be open to contributing docs to this entire package really as I am going to be writing them up for my org (more specific examples but can de proprietize and submit)

2022-01-31 16:38 UTC, jayceslesar commented
Was able to get around this by building uglier regexes so not needed!

2022-01-31 22:26 UTC, closed without merging